---
- name: Get the username running task
  shell:
    cmd: whoami
  register: user_on_the_host

- name: Update the /root/.bashrc file
  lineinfile:
    dest: "/root/.bashrc"
    line: "export {{ item.var }}='{{ item.value }}'"
    state: present
  loop:
    - { var: 'AWS_ACCESS_KEY_ID', value: "{{ AWS_ACCESS_KEY_ID }}" }
    - { var: 'AWS_SECRET_ACCESS_KEY', value: "{{ AWS_SECRET_ACCESS_KEY }}" }
    - { var: 'AWS_DEFAULT_REGION', value: "{{ AWS_REGION }}" }
  when: user_on_the_host.stdout == 'root'

- name: Update the /home/{{ user_on_the_host.stdout }}/.bashrc file
  lineinfile:
    dest: "/home/{{ user_on_the_host.stdout }}/.bashrc"
    line: "export {{ item.var }}='{{ item.value }}'"
    state: present
  loop:
    - { var: 'AWS_ACCESS_KEY_ID', value: "{{ AWS_ACCESS_KEY_ID }}" }
    - { var: 'AWS_SECRET_ACCESS_KEY', value: "{{ AWS_SECRET_ACCESS_KEY }}" }
    - { var: 'AWS_DEFAULT_REGION', value: "{{ AWS_REGION }}" }
  when: user_on_the_host.stdout != 'root'
